### ISSUE TITLE
關於setting.cfg

### ISSUE THREAD

**Issue by d1210182010** [h9896/JSUN-Future-API#1]
您好

想請教`setting.cfg`的IPSERVER應如何正確設定（`SYS_MSG999:IP主機連線異常`），以及cmd.txt的使用範例

謝謝

**Comment by h9896** [comment]
IPSERVER 應是日盛那邊主機的IP
https://jsmarket.jihsun.com.tw/futures/globaltrader/api.html
這是日盛API的網頁
正確IP可能要問日盛那邊

cmd的方面就是開啟程式後，在txt輸入指令後按儲存，程式便會執行該指令

**Comment by d1210182010** [comment]
謝謝！向日盛詢問已解決

想再請問憑證問題`SYS_MSG999:[ 999 ] CaVerify Error : 您沒有申請憑證，以致您不能下單!`如何處理嗎？
現在使用的環境憑證設定應是正常的（過官網憑證檢測+可正常下單）

**Comment by h9896** [comment]
不好意思，我不是日盛的人，只是練習串接而已
這個問題可能是你用64位元開啟程式
但是他們的憑證好像只有32位元
所以要用32位元的python

**Comment by d1210182010** [comment]
了解，百忙之中打擾，感謝您！
